import os
from fpdf import FPDF

OUTPUT_DIR = "documents"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def save_pdf(filename: str, content_fn):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    content_fn(pdf)
    path = os.path.join(OUTPUT_DIR, filename)
    pdf.output(path)
    print(f"  Created: {path}")


# Invoices Data

def invoice_1(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "ACME CORPORATION", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Invoice Number: INV-1001", ln=True)
    pdf.cell(0, 8, "Date: January 15, 2025", ln=True)
    pdf.cell(0, 8, "Company: ACME Corporation", ln=True)
    pdf.cell(0, 8, "Bill To: XYZ Traders, Lahore, Pakistan", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Item Description         Qty    Unit Price    Amount", ln=True)
    pdf.cell(0, 8, "Web Development Services  1      $300.00       $300.00", ln=True)
    pdf.cell(0, 8, "Hosting (Annual)          1      $50.50        $50.50", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Subtotal: $350.50", ln=True)
    pdf.cell(0, 8, "Tax (0%): $0.00", ln=True)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Total Amount: $350.50", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.ln(4)
    pdf.cell(0, 8, "Payment Due: February 15, 2025  |  Net 30", ln=True)


def invoice_2(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "TechSoft Solutions Pvt. Ltd.", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Invoice No: INV-2048", ln=True)
    pdf.cell(0, 8, "Date: 03/10/2025", ln=True)
    pdf.cell(0, 8, "Vendor: TechSoft Solutions Pvt. Ltd.", ln=True)
    pdf.cell(0, 8, "Bill To: National Bank Ltd.", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "AI Consulting Services         $1,200.00", ln=True)
    pdf.cell(0, 8, "Model Training Support         $800.00", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Subtotal: $2,000.00", ln=True)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Grand Total: $2,000.00", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 8, "Due Date: April 10, 2025  |  Net 30", ln=True)


def invoice_3(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "GLOBALINK LOGISTICS", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Invoice Number: INV-7891", ln=True)
    pdf.cell(0, 8, "Date: 2025-07-01", ln=True)
    pdf.cell(0, 8, "From: Globalink Logistics, Karachi", ln=True)
    pdf.cell(0, 8, "Sold To: Punjab Textile Mills", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Freight Charges (International):   $5,400.00", ln=True)
    pdf.cell(0, 8, "Custom Clearance Fee:              $600.00", ln=True)
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Total Amount Due: $6,000.00", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 8, "Payment Due: 30 days from invoice date", ln=True)


# Resumes Data

def resume_1(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "John Doe", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Email: john.doe@gmail.com  |  Phone: 123-456-7890", ln=True, align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Objective", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Experienced software engineer seeking challenging AI/ML role.", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Work Experience", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Senior ML Engineer - DataVision Inc. (2019-2024) - 5 years of experience", ln=True)
    pdf.cell(0, 8, "Junior Developer - SoftBase (2017-2019)", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Education", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "B.Sc. Computer Science - MIT, 2017  |  GPA: 3.8", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Skills", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Python, PyTorch, TensorFlow, LangChain, Docker, AWS", ln=True)


def resume_2(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Sara Ahmed", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "sara.ahmed@outlook.com  |  +92-333-9876543", ln=True, align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Career Objective", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Data scientist with 3 years of experience in NLP and deep learning.", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Professional Experience", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "NLP Engineer - Kognitive AI (2022-2025) - 3 yrs experience", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Education", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "M.Sc. Data Science - LUMS, 2022", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Certifications", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "DeepLearning.AI Specialization, HuggingFace NLP Course", ln=True)


def resume_3(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Ali Hassan", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "ali.hassan@yahoo.com  |  0300-1234567", ln=True, align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Summary of Qualifications", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Full-stack developer with 7 years of experience in web technologies.", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Employment History", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "Lead Developer - ByteWorks (2018-2025) - 7 years experience", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Education", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "B.Sc. Software Engineering - FAST NUCES, 2018  |  GPA: 3.5", ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Skills & Languages", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, "React, Node.js, PostgreSQL, Docker, Kubernetes, English, Urdu", ln=True)
    pdf.cell(0, 8, "References available upon request.", ln=True)


# Utility Bills Data

def utility_1(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "LESCO - Lahore Electric Supply Company", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Account Number: LESCO-8821-44X", ln=True)
    pdf.cell(0, 8, "Billing Period: January 2025", ln=True)
    pdf.cell(0, 8, "Service Address: House 12, Block C, Johar Town, Lahore", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Meter Number: MTR-00291", ln=True)
    pdf.cell(0, 8, "Previous Reading: 4200 kWh", ln=True)
    pdf.cell(0, 8, "Current Reading: 4560 kWh", ln=True)
    pdf.cell(0, 8, "Total Consumption: 360 kWh", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Energy Charges:   Rs. 4,320", ln=True)
    pdf.cell(0, 8, "Fixed Charges:    Rs. 500", ln=True)
    pdf.cell(0, 8, "Taxes:            Rs. 180", ln=True)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Amount Due: Rs. 5,000", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 8, "Due Date: February 5, 2025", ln=True)


def utility_2(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "SNGPL - Sui Northern Gas Pipelines Ltd.", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Account No: SNGPL-3349-GZ", ln=True)
    pdf.cell(0, 8, "Billing Period: March 2025", ln=True)
    pdf.cell(0, 8, "Consumer Address: Flat 7, DHA Phase 5, Lahore", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Gas Consumption: 12 kWh equivalent", ln=True)
    pdf.cell(0, 8, "Tariff: Domestic Slab 2", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Current Charges:   Rs. 1,200", ln=True)
    pdf.cell(0, 8, "Previous Balance:  Rs. 0", ln=True)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Amount Due: Rs. 1,200", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 8, "Please pay before April 10, 2025", ln=True)


def utility_3(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "WASA - Water & Sanitation Agency", ln=True, align="C")
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Account Number: WASA-LHR-00482", ln=True)
    pdf.cell(0, 8, "Date: May 1, 2025", ln=True)
    pdf.cell(0, 8, "Service Address: 88-B, Model Town, Lahore", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Water Usage: 45 kWh equivalent units", ln=True)
    pdf.cell(0, 8, "Connection Type: Residential", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Water Charges:  Rs. 850", ln=True)
    pdf.cell(0, 8, "Sewerage:       Rs. 150", ln=True)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Total Amount Due: Rs. 1,000", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 8, "Bill Period: April 2025", ln=True)


# Other document Data

def other_doc(pdf: FPDF):
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Company Meeting Minutes", ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.ln(4)
    pdf.cell(0, 8, "Meeting Date: April 20, 2025", ln=True)
    pdf.cell(0, 8, "Attendees: CEO, CTO, HR Manager, Legal Team", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Agenda:", ln=True)
    pdf.cell(0, 8, "1. Quarterly performance review", ln=True)
    pdf.cell(0, 8, "2. New product launch timeline", ln=True)
    pdf.cell(0, 8, "3. Hiring plan for Q3 2025", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Decisions Made:", ln=True)
    pdf.cell(0, 8, "- Product launch moved to June 2025", ln=True)
    pdf.cell(0, 8, "- 5 new engineers to be hired by July", ln=True)
    pdf.cell(0, 8, "- Marketing budget approved at $20,000", ln=True)
    pdf.ln(4)
    pdf.cell(0, 8, "Next Meeting: May 20, 2025", ln=True)


# Generate all kind of data

if __name__ == "__main__":
    print(f"\n Generating demo PDFs in '{OUTPUT_DIR}/'...\n")

    save_pdf("invoice_1.pdf", invoice_1)
    save_pdf("invoice_2.pdf", invoice_2)
    save_pdf("invoice_3.pdf", invoice_3)
    save_pdf("resume_1.pdf",  resume_1)
    save_pdf("resume_2.pdf",  resume_2)
    save_pdf("resume_3.pdf",  resume_3)
    save_pdf("utility_1.pdf", utility_1)
    save_pdf("utility_2.pdf", utility_2)
    save_pdf("utility_3.pdf", utility_3)
    save_pdf("other_1.pdf",   other_doc)

    print(f"\n Done - 10 demo documents created in '{OUTPUT_DIR}/'")
    print("Now run: python main.py")
